entries_per_file: 700
start_ends:
- - ཀ
  - འགལ་བ་བརྗོད་པའི་ཐལ་འགྱུར།
- - འགལ་བའི་གཏན་ཚིགས།
  - ཆོས་ཁམས་ཀྱི་སེམས་བྱུང་།
- - ཆོས་འཁོར།
  - ཐག་ཅིག་ཏུ་ཆད་པ།
- - ཐག་གཅིག་ཐོག་ཏུ་བཅད་པ།
  - འདོད་ཆགས།
- - འདོད་ཆགས་ཀྱི་ཁམས།
  - ཕྱམ་བརྡལ།
- - ཕྱམ་གནས།
  - མ་ཡེངས།
- - མ་གཡེང་བ།
  - ཝ་ལེར།
- - ཝརྟུ།
  - རང་རྒྱུད་དབུ་མ་པ།
- - རང་རྒྱུད་ལ་གྲུབ་པ།
  - ས་ལེ།
- - ས་ལེ་བ།
  - ཨོཾ་སྭསྟི།
