entries_per_file: 1000
start_ends:
- - ཀ
  - ངོ་ལྐོག
- - ངོ་སྐོག
  - བརྟེན་པ།
- - བརྟེན་པའི་དཀྱིལ་འཁོར།
  - རྣམ་རྟོག
- - རྣམ་རྟོག་གྲོལ།
  - སྦྱོར་བྱུང་གི་རྒྱུ།
- - སྦྱོར་ལམ།
  - ཟློག་པ།
- - གཟའ།
  - ཤིང་རྟ་ཆེན་པོ་བརྒྱད།
- - ཤིང་རྟའི་སྲོལ་གཉིས།
  - ཨོཾ་སྭསྟི།
